Assignment 1 - Working with NumPy
In this assignment, we perform various operations using the NumPy library, including array creation, statistical calculations, reshaping, and matrix operations.

In [1]:
import numpy as np


arr_1d = np.arange(1, 21)


print("Sum:", np.sum(arr_1d))
print("Mean:", np.mean(arr_1d))
print("Median:", np.median(arr_1d))
print("Standard Deviation:", np.std(arr_1d))


indices = np.where(arr_1d > 10)
print("Indices of elements > 10:", indices)


arr_2d = np.arange(1, 17).reshape(4, 4)


print("\n4x4 Array:\n", arr_2d)


print("Transpose:\n", arr_2d.T)


print("Row-wise sums:", np.sum(arr_2d, axis=1))
print("Column-wise sums:", np.sum(arr_2d, axis=0))


array1 = np.random.randint(1, 21, (3, 3))
array2 = np.random.randint(1, 21, (3, 3))

print("\nArray 1:\n", array1)
print("Array 2:\n", array2)


print("Addition:\n", array1 + array2)
print("Subtraction:\n", array1 - array2)
print("Multiplication:\n", array1 * array2)


print("Dot Product:\n", np.dot(array1, array2))


arr_size_12 = np.arange(12)
reshaped_arr = arr_size_12.reshape(3, 4)
sliced_arr = reshaped_arr[:2, -2:]

print("\nReshaped 3x4 Array:\n", reshaped_arr)
print("Sliced Array (First 2 rows, last 2 columns):\n", sliced_arr)

Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]

Array 1:
 [[14 19  1]
 [12  9 19]
 [ 5  7  5]]
Array 2:
 [[12  8 18]
 [12 17 15]
 [15  6  2]]
Addition:
 [[26 27 19]
 [24 26 34]
 [20 13  7]]
Subtraction:
 [[  2  11 -17]
 [  0  -8   4]
 [-10   1   3]]
Multiplication:
 [[168 152  18]
 [144 153 285]
 [ 75  42  10]]
Dot Product:
 [[411 441 539]
 [537 363 389]
 [219 189 205]]

Reshaped 3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sliced Array (First 2 rows, last 2 columns):
 [[2 3]
 [6 7]]
